# Dockerfile
FROM ubuntu:22.04

# Install Python and required packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python libraries
RUN pip3 install \
    kafka-python \
    psycopg2-binary \
    pyspark \
    delta-spark

# Copy the project files into the container
WORKDIR /app
COPY . /app

# Default command (change as needed)
CMD ["python3", "qa_checks.py"]
